site:
  name: Foseer
  site: 'https://foseer.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: ''

# Default SEO metadata
metadata:
  title:
    default: Foseer
    template: '%s — Foseer'
  description: 'Foseer is a news and insights site highlighting what matters now in business, technology, politics, society, and culture.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Foseer
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
        alt: 'Foseer - News and insights site'
    type: website
    locale: 'en_US'
  twitter:
    handle: ''
    site: ''
    cardType: summary_large_image
    creator: ''

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/article/%slug%'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'latest'
      robots:
        index: true

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'
